name: iqchannels
description: "A new Flutter project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.iqchannels
        pluginClass: IqchannelsPlugin
      ios:
        pluginClass: IqchannelsPlugin
      linux:
        pluginClass: IqchannelsPlugin
      macos:
        pluginClass: IqchannelsPlugin
      windows:
        pluginClass: IqchannelsPluginCApi
      web:
        pluginClass: IqchannelsWeb
        fileName: iqchannels_web.dart

